### PR TITLE
Syntax and macro updates

### PR DESCRIPTION
**Pull request by brandonwillard**
Just some recent updates.

Otherwise, I would like to move more toward the `python.el` method of handling processes; that way, one can run independent processes based only on processes naming (e.g. per-venv processes with `*Python[my-venv-name]*` named-buffers)

### CODE REVIEW

**Comment by ekaschalk** [comment]
Thanks for the PR. Process handling in general could be improved in hy-mode, this aspect is where development has stalled at recently. I'll be doing a pass-through soon so hopefully then we can address this class of updates.

**Comment by brandonwillard** [comment]
Oh, I have some more for this!  Going through the tests currently, but there are a few process-handling updates (just the use of one function for naming, really).

**Comment by brandonwillard** [comment]
No prob, though; I'll put in another PR for those changes.  One minute...

**Comment by ekaschalk** [comment]
For me, tests are exactly where I stalled out, found it difficult to test process/comint-mode stuff. The dev branch I use cask and have tests for most other stuff but I don't think its solid enough/complete to replace master yet.

**Pull request merged**
